version: "3.8"
services:
  react-app:
    build: ../../..
    container_name: react-app
    restart: always
    ports:
      - "81:81"
    networks:
      react_network:
    depends_on: backend
  backend:
    image:
      node:18
    container_name: backend_service
    working_dir: /app
    volumes:
      - ./backend:/app
    command:
      - "npm start"
    ports:
      - "3000:3000"
    networks:
      react_network: