apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: firstprojekt
  name: firstprojekt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firstprojekt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: firstprojekt
    spec:
      containers:
      - image: iryna-kosiakovska/firstprojekt:1.0.3-SNAPSHOT
        name: back
        resources: {}
status: {}
