apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: front-ingress-quarkus
spec:
  rules:
  - host: localhost
    http:
      paths:
      - backend:
          service:
            name: front-service-quarkus
            port:
              number: 3000
        path: /
        pathType: Prefix
status:
  loadBalancer: {}
