apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: firstprojekt
spec:
  rules:
  - host: localhost
    http:
      paths:
      - backend:
          service:
            name: firstprojekt
            port:
              number: 81
        path: /api/
        pathType: Prefix
status:
  loadBalancer: {}
