apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: firstprojekt
  name: firstprojekt
spec:
  ports:
  - name: 81-8081
    port: 81
    protocol: TCP
    targetPort: 8081
  selector:
    app: firstprojekt
  type: ClusterIP
status:
  loadBalancer: {}
